### ISSUE TITLE
Wrong endpoint

### ISSUE THREAD

**Issue by techtonik** [fedora-infra/mdapi#1]
https://apps.fedoraproject.org/mdapi links are all dead. Where is the deployed server?

**Comment by pypingou** [comment]
hm there is something wrong in there indeed, I'll look into it, but basically there is a ``/mdapi/`` missing, for example:

* invalid: https://apps.fedoraproject.org/branches
* valid: https://apps.fedoraproject.org/mdapi/branches

**Comment by techtonik** [comment]
Nice. Useful service. Is it possible also to make JSON human readable?

**Comment by puiterwijk** [comment]
If you add ?pretty=True at the end of the URL, it will be human readable.

**Comment by techtonik** [comment]
That's not convenient - as a human I have no chance to know that, It would be better to return compressed stuff for ajax calls.

**Comment by ralphbean** [comment]
@techtonik you can install a browser plugin to make JSON pretty-printed by default.  JSONovich is one for Firefox.

**Comment by pypingou** [comment]
> as a human I have no chance to know that

This is a 'bug' in the documentation, I mentioned it in my blog post: http://blog.pingoured.fr/index.php?post/2015/11/19/Introducing-mdapi but it's not on the index page, we should probably fix this.

> It would be better to return compressed stuff for ajax calls.

What do you mean?

**Comment by techtonik** [comment]
I mean why do this is returned in non human format in the first place? First reason that I hear is that this format is more compact and saves bandwidth. Second reason is that it saves memory and processing power. I find these two less important that human accessibility.

If that micro-optimizations are important (but think of minute of YouTube traffic) then it is possible to detect when resource is accessed by non-humans and return compressed form only for them. For example with
https://stackoverflow.com/questions/17478731/whats-the-point-of-x-requested-with-header

**Comment by techtonik** [comment]
And about http://blog.pingoured.fr/index.php?post/2015/11/19/Introducing-mdapi - looks like you have everything in place to test actual performance of `?pretty=True`

**Comment by ralphbean** [comment]
Hm, 'mdapi' has "API' in the name.  I think it would be a cool project to build a different site that queries the mdapi api and presents the data in a human readable way.

**Comment by techtonik** [comment]
Do you have some funding for that?

**Comment by pypingou** [comment]
I think it's less a matter of funding than a matter of interest. I wanted to build an api to expose as fast as possible the data present in the yum repositories, the goal of this api was to be usable for another web application: https://apps.fedoraproject.org/packages

**Comment by tyll** [comment]
On So, Nov 22, 2015 at 06:16:30 -0800, Ralph Bean wrote:
> Hm, 'mdapi' has "API' in the name.  I think it would be a cool project
> to build a different site that queries the mdapi api and presents the
> data in a human readable way.

IMHO it is nice to show human readable output if it is likely that a
human watches the output. Not sure if an extra project that just pretty
prints the output of mdapi to be able to easily unterstand it is worth
it. An idea to fuzzy match pretty print is shown in PR #2 (not tested).

Regards
Till

**Comment by pypingou** [comment]
The original problem of this ticket has been solved in 2.2.2 now running in prod. I am therefore closing this ticket.
As for the discussion around the output returned, mdapi is not meant for human consumption, the prettified version of its output is merely there to facilitate the life of developer using it for the first time but is not meant to be used regularly. If it is such a big problem, I could also just remove it, after all it wasn't there before  2.0.

Thanks for your report.

**Comment by pypingou** [comment]
PS: I'm now disabling tickets on github as mdapi is principally hosted on https://pagure.io/mdapi
