### ISSUE TITLE
Is this the currently used source code?

### ISSUE THREAD

**Issue by voxik** [fedora-infra/mdapi#34]
Hi, I am facing this issue:

https://github.com/fedora-infra/the-new-hotness/issues/539

and it was identified as issue in MDAPI reported here:

https://pagure.io/mdapi/issue/115

But I am not sure anymore, if the mdapi from pagure is the currently used source code or this is this the right place and the current code? Or what is the plan if it si not the currently deployed code.

**Comment by voxik** [comment]
It seems that the current instance is still the Pagure one, otherwise the footer would contain this line:

https://github.com/fedora-infra/mdapi/blob/e9d4439d92b3b5d0ab159f65e9a538ec00067854/mdapi/services/homepage.html#L182

So what is the timeline to have this deployed? I wonder if I should try to analyze the issue in the old version or in this one (actually I already understand where the issue is in the current instance).

**Comment by gridhead** [comment]
The Pagure one receives bug fixes but once this is deployed (which I plan to look into at the start of Q1 2022, as a lot of infrastructure folks are on leave), I think that would get archived.

**Comment by voxik** [comment]
Thx for clarification. Would you consider backporting #36 into the Pagure version or will it wait until this becomes the official deployment repo?

**Comment by gridhead** [comment]
@voxik, I don't think there would be a need of backporting that pull request as this is where the project is maintained from now. The [staging deployments](https://mdapi.stg.fedoraproject.org/) have been made and has been informed to the community on the official [devel mailing list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/KAZOUBVPGV62UKESGNKOTWW554QDEX4Q/) and on the [infrastructure mailing list](https://lists.fedoraproject.org/archives/list/infrastructure@lists.fedoraproject.org/thread/KAZOUBVPGV62UKESGNKOTWW554QDEX4Q/). This should soon make it to the production environment too.

**Comment by voxik** [comment]
Thx for taking care about this. I don't think there is anything else to discuss here :)
