### ISSUE TITLE
Support zstd compression

### ISSUE THREAD

**Issue by dralley** [fedora-infra/mdapi#96]
createrepo_c is adding support for zstd-compressed metadata, which has a lot of benefits. I intend to push for this to be used by Fedora eventually.

(I'll submit a PR for this later, it should be very easy to add)

**Comment by gridhead** [comment]
Assigned this ticket to you for now.

Could you please let me know about the benefits that you mentioned, that would come if the zstd compression is implemented?

**Comment by dralley** [comment]
Well the benefits to mdapi, assuming zstd-compressed-metadata were adopted by Fedora, would just be that mdapi wouldn't immediately break if/when they turn it on.

In terms of being adopted by Fedora - DNF already supports it, it's just a matter of producing the metadata.  You can read https://github.com/rpm-software-management/createrepo_c/pull/345 but the TL;DR version is faster decompression and smaller metadata file sizes.

**Comment by gridhead** [comment]
Understood.

Would you want me to wait until https://github.com/rpm-software-management/createrepo_c/pull/345 is merged before we merge the PR associated with this issue ticket?

**Comment by dralley** [comment]
Thanks!
